-- One record for every file LeRoutier holds, whichever provider holds it.
--
-- WHY A NEW TABLE RATHER THAN MORE COLUMNS ON verification_evidence.
--
-- verification_evidence already stores an object key and a provider, and it
-- stays exactly as it is: it is a REVIEW WORKFLOW (pending / verified /
-- rejected, a reviewer, notes, a 90-day redaction for refused dossiers). What
-- it is not is a registry of stored files — it has no application-owned
-- identifier, no checksum, no bucket, and no way to describe a photograph of a
-- delivered parcel at all.
--
-- This table is that registry, and it is the one place a stored object is
-- described. It does NOT replace verification_evidence, and this migration
-- does not touch it. The adoption path is stated here so it is not rediscovered
-- later: when the provider cutover happens, verification_evidence gains a
-- nullable `media_id` pointing here, the managed rows are backfilled, and its
-- own storage_key / storage_provider / content_type / byte_size columns are
-- dropped once nothing reads them. Until then the KYC path is untouched, which
-- is the point — production file writes do not change in this migration.
--
-- THE MEDIA ID IS THE CONTRACT. `id` is generated by the application, is
-- opaque, and NEVER changes: no client ever sees a provider, a bucket or an
-- object key, and no business table or client state stores a provider URL as
-- the canonical reference. `object_key` is internal and may be re-pointed at a
-- different provider without any caller noticing — which is the whole reason
-- the identifier is ours rather than the vendor's.
--
-- NO BLOBS IN POSTGRESQL. Stated in 007 and true here: this table describes
-- where bytes live, it never holds them.
CREATE TABLE IF NOT EXISTS media (
  -- The internal key: what foreign keys and the audit trail point at. The audit
  -- event stream types its entity_id as a uuid, and an audit trail that cannot
  -- name the thing it audited is not an audit trail.
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- `med_` plus 26 base32 characters: immutable, application-owned, and the
  -- ONLY identifier any caller ever handles. Kept beside the uuid rather than
  -- instead of it, exactly as parcels keep a uuid primary key beside their
  -- human-facing tracking_number — the uuid is how the platform refers to a
  -- row, the media id is how the outside world does.
  media_id text NOT NULL UNIQUE CHECK (media_id ~ '^med_[A-Z2-7]{26}$'),

  -- WHO IT BELONGS TO, and WHOM IT IS ABOUT. These differ more often than they
  -- look: an operator's registration certificate is owned by the administrator
  -- who uploaded it and is about the company, while a driver's photograph is
  -- owned by that driver and is about them. Account deletion is driven by
  -- owner_user_id, and a deletion path that forgot to remove a subject's files
  -- would be the one that mattered most.
  owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_user_id uuid REFERENCES users(id) ON DELETE CASCADE,

  -- What the file is FOR. Deliberately a closed list: every value here is a
  -- claim the product makes about retention and about who may open it, and a
  -- free-text purpose would quietly become a way to avoid both.
  purpose text NOT NULL CHECK (purpose IN (
    'operator_kyc','driver_kyc','vehicle_document','driver_photo','vehicle_photo',
    'parcel_delivery_evidence','parcel_pickup_evidence','incident_evidence')),

  -- WHERE THE BYTES ACTUALLY ARE, today. Provider is a word LeRoutier owns
  -- ('b2', 'neon'), not a vendor URL, so moving an object between providers is
  -- a row update rather than a schema change.
  provider text NOT NULL CHECK (provider ~ '^[a-z0-9_-]{2,32}$'),
  bucket text NOT NULL,
  object_key text NOT NULL,

  -- NEVER a URL and never derivable into one. The traversal check is defence in
  -- depth: a key is always generated by us, but a key that can be made to
  -- escape its bucket is the kind of mistake that is only discovered after it
  -- has been used, so the database refuses the shape outright.
  CONSTRAINT media_object_key_is_a_key CHECK (
    length(object_key) BETWEEN 1 AND 512
    AND object_key !~ '\.\.'
    AND object_key !~ '^/'
    AND object_key !~ '://'),

  content_type text NOT NULL,
  byte_size bigint NOT NULL CHECK (byte_size > 0),
  -- Recorded at upload from the bytes LeRoutier actually received, and checked
  -- again after any copy. An object whose checksum does not match its row is
  -- not the file the row claims.
  checksum_sha256 text NOT NULL CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),

  -- Private unless a human deliberately decided otherwise, which is the default
  -- for everything: identity documents, parcel evidence and other personal
  -- files are private by construction.
  --
  -- `public_read` means any SIGNED-IN caller may open it without an ownership
  -- check — a driver's photograph, which every passenger on a matching journey
  -- sees. It does NOT mean anonymous: serving files to unauthenticated callers
  -- is a capability nothing needs yet, and it is not added speculatively. Even
  -- a `public_read` object is opened through a grant minted here, so expiry and
  -- revocation still apply and a bare bucket URL never reaches a client.
  visibility text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private','public_read')),

  -- `pending` is a row written before its object exists, so an upload that
  -- fails leaves evidence rather than a silence; `missing` is an object the
  -- store no longer has, which is what a reconciliation run records.
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','stored','missing','deleted')),

  -- Domain association. Nullable because a file may belong to none of them
  -- (an incident photograph), and CASCADE because these are parts of the
  -- entity rather than history that must survive it.
  operator_id uuid REFERENCES operators(id) ON DELETE CASCADE,
  parcel_id uuid REFERENCES parcels(id) ON DELETE CASCADE,
  vehicle_id uuid REFERENCES vehicles(id) ON DELETE CASCADE,

  created_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,

  -- One object, one row. Makes a re-run of a copy idempotent by construction:
  -- the second insert conflicts rather than inventing a second record of the
  -- same bytes.
  CONSTRAINT media_object_is_unique UNIQUE (provider, bucket, object_key)
);

-- The live rows, by owner: every read LeRoutier performs starts from one of
-- these and never from a scan.
CREATE INDEX IF NOT EXISTS media_owner_live ON media(owner_user_id) WHERE status <> 'deleted';
CREATE INDEX IF NOT EXISTS media_subject_live ON media(subject_user_id) WHERE status <> 'deleted';
CREATE INDEX IF NOT EXISTS media_parcel ON media(parcel_id) WHERE parcel_id IS NOT NULL AND status <> 'deleted';
CREATE INDEX IF NOT EXISTS media_vehicle ON media(vehicle_id) WHERE vehicle_id IS NOT NULL AND status <> 'deleted';
-- Reconciliation looks for exactly this: objects claimed but not confirmed,
-- and objects the store has lost.
CREATE INDEX IF NOT EXISTS media_by_status ON media(status) WHERE status <> 'stored';
