import { Navigate, useLocation, useNavigate } from 'react-router';
import{AppShell,Card,Badge,StatCard,SectionTitle}from'@leroutier/ui';import{Route,UserRound,QrCode,Clock3,Luggage,CloudOff,CheckCircle2,AlertTriangle,PhoneCall,BusFront,WalletCards,Gauge,ShieldCheck,Camera,Users,LogIn,LogOut,Navigation,Leaf,Receipt,Radio}from'lucide-react';
const nav=[{id:'route',label:'Feuille de route',icon:Route},{id:'profile',label:'Profil & bord',icon:UserRound}];
const passengers=[['04B','Adissou Michel','Descend à Bohicon','logout','Débarqué'],['14A','Yao Amevi Sossou','Vers Parakou','aboard','À bord'],['22C','Chantal Dossou','Monte à Bohicon','login','À pointer']];
function RouteScreen(){return <><Card className="card-dark stack"><div className="between wrap"><div><span className="eyebrow" style={{color:'#a7f3d0'}}>En route · RNIE2</span><h2>Cotonou → Bohicon → Dassa → Parakou</h2></div><Badge tone="success">Bus #BE-409-RB</Badge></div><div className="progress"><span style={{width:'42%',background:'#68dba9'}}/></div><div className="between small"><span>Chauffeur: Mathieu Dossou</span><strong>ETA Bohicon 08:45</strong></div></Card><div className="grid grid-3"><StatCard label="À bord" value="38/42" icon={Users} tone="success"/><StatCard label="Montent à Bohicon" value="+4" icon={LogIn} tone="primary"/><StatCard label="Colis scellés" value="45" icon={Luggage}/></div><Card className="scanner"><div className="between"><div><h2>Scanner billet passager</h2><span className="small">Validation QR, code manuel et cache hors-ligne</span></div><Badge>Caméra prête</Badge></div><div className="viewfinder"><QrCode size={58}/></div><div className="grid grid-2"><button className="btn btn-soft"><Camera size={17}/>Activer scanner</button><button className="btn btn-dark">Code manuel</button></div><div className="row small"><CloudOff size={15}/><strong>Mode station hors-ligne disponible</strong></div></Card><SectionTitle icon={Users} title="Manifeste passagers" trailing={<Badge>Étape: Bohicon</Badge>}/><div className="controls"><button className="control active">Tous (38)</button><button className="control">Montent (4)</button><button className="control">Descendent (6)</button><button className="control">Vers Parakou (28)</button></div><div className="stack">{passengers.map(([seat,name,detail,status,label])=><div className="manifest-row" key={seat}><div className="seat"><small>Siège</small><strong>{seat}</strong></div><div><h3>{name}</h3><div className="row small muted">{status==='login'?<LogIn size={14}/>:status==='logout'?<LogOut size={14}/>:<Navigation size={14}/>} {detail}</div><span className="small muted">Bagages enregistrés · paiement confirmé</span></div>{status==='login'?<button className="btn btn-primary"><QrCode size={15}/>Pointer</button>:<Badge tone="success"><CheckCircle2 size={13}/>{label}</Badge>}</div>)}</div><Card className="stack"><span className="eyebrow">Actions terrain</span><button className="btn btn-primary"><CheckCircle2 size={18}/>Clôturer embarquement Bohicon</button><button className="btn btn-danger"><AlertTriangle size={18}/>Signaler incident / panne</button></Card></>}
function Profile(){return <><Card className="stack"><div className="profile-block"><div className="profile-avatar">MD</div><div><h2>Mathieu Dossou</h2><span className="small muted">#CH-BEN-409 · Chauffeur vérifié</span><div><Badge tone="success">En service actif</Badge></div></div></div></Card><Card className="stack"><SectionTitle icon={BusFront} title="Affectation véhicule"/><div className="notice"><strong>Baobab Express #BE-409-RB</strong><br/>VIP Grand Confort · 52 places · climatisation & Wi‑Fi</div><div className="between small"><span>Visite technique CNSR</span><Badge tone="success">Valide</Badge></div></Card><div className="grid grid-2"><StatCard label="Ponctualité" value="98.4%" hint="Top 5% conducteurs" icon={Clock3} tone="success"/><StatCard label="Liaisons faites" value="18" hint="Interurbaines RNIE" icon={Route} tone="primary"/></div><Card className="stack"><SectionTitle icon={WalletCards} title="Frais de route"/><strong style={{fontSize:25}}>42 000 FCFA</strong><span className="small muted">Per diem, péages et gazole · validé régulation</span><div className="grid grid-2"><button className="btn btn-soft"><Receipt size={16}/>Historique</button><button className="btn btn-primary"><Camera size={16}/>Justifier ticket</button></div></Card><Card className="stack"><SectionTitle icon={ShieldCheck} title="Conformité & documents"/><div className="between"><div><strong>Permis D & aptitude médicale</strong><div className="small muted">Expire décembre 2026</div></div><CheckCircle2 color="#059669"/></div><div className="between"><div><strong>Assurance & carte grise</strong><div className="small muted">Police flotte #9822-AX</div></div><CheckCircle2 color="#059669"/></div></Card><Card className="stack"><SectionTitle icon={Gauge} title="Outils embarqués"/><div className="grid grid-2"><div className="service-chip"><Radio size={16}/>GPS synchronisé</div><div className="service-chip"><QrCode size={16}/>Scanner prêt</div><div className="service-chip"><Leaf size={16}/>Écoconduite +25k</div><div className="service-chip"><CloudOff size={16}/>Cache hors-ligne</div></div></Card><button className="btn btn-dark"><PhoneCall size={17}/>Appel régulation centrale</button></>}
export default function App() {
  const { pathname } = useLocation();
  const navigate = useNavigate();
  const page = pathname.replace(/\/$/, '').slice(1) || 'route';
  if (page !== 'route' && page !== 'profile') return <Navigate to="/" replace />;
  return <AppShell role="Chauffeur" title={page === 'route' ? 'Feuille de route & embarquement' : 'Profil & documents de bord'} subtitle="Console conducteur" nav={nav} active={page} onNavigate={id => navigate('/' + id)}>{page === 'route' ? <RouteScreen /> : <Profile />}</AppShell>;
}
